server:
  port: 8080

spring:
  application:
    name: rainwater-gateway

zuul:
  routes:
    collection-service:
      path: /collection/**
      url: http://localhost:8081
    purification-service:
      path: /purification/**
      url: http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/